openapi: '3.0.3'
info:
  title: API per la gestione dello stato dei servizi online del comune di trento (lato GdS)
  license:
    name: MIT
  version: '1.0'
servers:
  - url: https://localhost:8000/api/v1
    description: Server per le API del gestore del servizio
paths:
  /getinfo/servizio:
    get:
      summary: Ottiene informazioni su un servizio
      description: Restituisce un oggetto con il l'id, il nome, l'immagine, il link e l'azienda del servizio
      security:
        - BearerAuth: [GdS]  
      responses:
        '200':
          description: Dati gds prelevati con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 3923
                  nome:
                    type: string
                    example: "OnOff Trento"
                  link:
                    type: string 
                    format: link
                    example: "https://onofftrento.it"
                  email:
                    type: string
                    format: email
                    example: "onofftrento@trentino.trasporti.it"
                  azienda:
                    type: string
                    example: "Muoversi in Trentino" 
                  immagine:
                    type: string
                    format: binary
                  
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /delete/gds/{id}:
    delete:
      summary: Elimina il gds con l'id selezionato
      description: Elimina il GdS autenticato
      security:
        - BearerAuth: [Admin]  
      responses:
        '200':
          description: Utente eliminato
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /register/gds:
    post:
      summary: Manda una richiesta per registrare il servizio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "OnOff Trento"
                link:
                  type: string 
                  format: link
                  example: "https://onofftrento.it"
                email:
                  type: string
                  format: email
                  example: "onofftrento@trentino.trasporti.it"
                azienda:
                  type: string
                  example: "Muoversi in Trentino"
                password: 
                  type: string
                  format: password
                  example: "Password1234"
                immagine:
                  type: string
                  format: binary
              required:
                - nome
                - cognome
                - email
                - password
                - immagine
            
      responses:
        "201":
          description: Richiesta di registrazione del servizio mandata
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Errore nei dati forniti."
        "500":
          description: Richiesta non valida (servizio già presente)
          content:
            application/json:
              schema:
                type: string 
  /avvisi/rilascia:
    post:
      summary: Manda una segnalazione di disservizio
      security:
        - BearerAuth: [GdS]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tipo:
                  type: string
                  enum: ["manutenzione","problemi","offline"]
                periodo:
                  oneOf:
                    - type: object
                      properties:
                        inizio: 
                          type: string
                          format: date
                          example: "2024-01-01"
                        fine:
                          type: string
                          format: date
                          example: "2024-01-15"
                    - type: string
                      enum: ["indefinito"]
                  description: "Periodo in cui persiste il disservizio"
              required:
                - tipo
                - periodo
      responses:
        "201":
          description: segnalazione mandata con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  messaggio:
                    type: string
                    example: "Segnalazione mandata correttamente"
                  senalazioneId:
                    type: string
                    example: "sn-3421"
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Errore nei dati forniti."
  /avvisi/cancella/{avviso_id}:
    delete:
      summary: Elimina un avviso
      description: Elimina un avviso specifico per il servizio indicato
      security:
        - BearerAuth: [GdS]
      parameters:
        - name: avviso_id
          in: path
          description: ID del servizio dell'avviso
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Avviso eliminato con successo
    put:
      summary: Modifica un avviso
      description: Modifica un avviso specificato
      security:
        - BearerAuth: [GdS]
      parameters:
        - name: service_id
          in: path
          description: ID del servizio dell'avviso
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titolo:
                  type: string
                  description: Nuovo titolo dell'avviso
                messaggio:
                  type: string
                  description: Nuovo contenuto dell'avviso
      responses:
        '200':
          description: Avviso modificato con successo
  /gds/changeform:
    post:
      summary: Modifica il form di segnalazione dell'utente per quel determinato servizio
      security:
        - BearerAuth: [GdS]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/changeFormPost'
      responses:
        '201'
              


      

  /commenti:
    post:
      summary: Ottiene una lista di commenti
      description: Restituisce una lista di commenti
      requestBody: 
        required: true
        content:
          application/json:
            schema: 
              type: string
              properties:
                token:
                  type: string
                  example: "xsfsd23skd12"
      responses:
        '200':
          description: Lista di commenti recuperata con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    commentoId:
                      type: string
                      example: "com-12345"
                    autore:
                      type: string
                      example: "Mario Rossi"
                    testo:
                      type: string
                      example: "Questo è un commento di esempio."
                    data:
                      type: string
                      format: date-time
                      example: "2024-01-01T12:00:00"
        '400':
          description: Richiesta non valida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Errore nei parametri forniti."
        '404':
          description: Commenti non trovati
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Nessun commento trovato per questo servizio."
        
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    ForbiddenError:
      description: Access denied due to insufficient permissions
  schemas:
    changeFormPost:
      type: object
      properties:
        domande: 
          type: object
          properties:
            tipo:
              type: string
              enum: ["radio","multipla","singlecheck"]
            testo:
              type: string
        testo:
          type: string
        descrizione:
          type: string
                
